name: Go Syntax Check

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1

    - name: Check syntax
      run: go vet ./...
